### ISSUE TITLE
The right way to change default adapter in config.exs

### ISSUE THREAD

**Issue by zhongwencool** [zhongwencool/maxwell#51]
Maxwell has unquote `:default_adapter` from `config.exs`.
https://github.com/zhongwencool/maxwell/blob/master/lib/maxwell/builder.ex#L192
Now: the right way to change `:default_adapter`  should be
1. Change the `xxx.exs` in your own project;
```elixir
config :maxwell,
  default_adapter: Maxwell.Adapter.Httpc
```
2. Compile your own project by `mix compile`

3. Compile `:maxwell` due to the `maxwell.ex` should be recompiled too.
```elixir
mix deps.clean maxwell --build
mix deps.compile maxwell
```
Is there any simplified methods to achieve this?

This situation just like https://github.com/vt-elixir/ja_serializer#configuration.
ja_serializer just explain this in readme.

**Comment by secretworry** [comment]
I don't think it is necessary to provide options for user to modify the default configuration for Maxwell, since those defaults are used just for convenience. If the user needs other adapter, they should explicitely set it in his/her client, instead of modifing the default config to achieve it implicitely.

To achieve the result you want, we have to make the deps depend on the code of user, which breaks the structure of dependency graph.

**Comment by zhongwencool** [comment]
https://github.com/zhongwencool/maxwell/pull/53
