### ISSUE TITLE
Don't Reinvent HTTP Spec

### ISSUE THREAD

**Issue by rawkode** [zhongwencool/maxwell#68]
Currently, your library enforces that `get` / `delete` and `options` don't have a body, which violates the HTTP spec.

https://github.com/zhongwencool/maxwell/blob/c583e17a4870e651e2ff6f6e3df8746e446841f2/lib/maxwell/builder.ex#L48

**Comment by secretworry** [comment]
@rawkode the underlying libs' handling the DELETE with body vary(e.g. For example, the hackney treats 'PUT' and 'POST' separately when sending a binary as the body, [hackney_request.el](https://github.com/benoitc/hackney/blob/master/src/hackney_request.erl#L74)), so to adapt them, we took a shortcut to just disable it (we are considering supporting delete with body see #64 )
And I'm quite sure that sending a GET with body is useless, you can see more talk [here](https://stackoverflow.com/questions/978061/http-get-with-request-body)

So the best solution, for now, to work around the problem is to send a POST request with the magical *_method* param, many framework support this feature.

**Comment by rawkode** [comment]
Useless or not, it's part of the HTTP spec

https://tools.ietf.org/html/rfc2616

A common use-case is GraphQL

**Comment by secretworry** [comment]
@rawkode When serving the GraphQL through HTTP service, the query should be specified in the query parameter for a GET request(see [here](http://graphql.org/learn/serving-over-http/)).
By useless I mean the server SHOULD ignore the body according to the spec( more discussions can be found on the link in my previous comment), so sending a GET with a body should be considered as a misuse, and we should warn our user for that:)
